name: "Checkout and restore dependencies"
description: "Checkouts repo and restores dependencies"
runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: node_modules
        key: node-modules-${{ hashFiles('package-lock.json') }}