name: nx-loki CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}

env:
  CI: true

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/cache/restore@v4
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}